name: Pre-release

# Prepares a new release
#
# To trigger it, simply change the CHANGELOG.md file, replacing the
# "Unreleased" header text with the new release's version number.
#
# The workflow will automatically prepare a pull request for the release.
#

on:
  push:
    branches: [main]

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    name: Create / Update Release PR
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
     - uses: cucumber/actions-get-versions@v1.0.0
        id: versions
      - uses: cucumber/action-create-release-pr@v1.1.0
        if: steps.versions.outputs.is-release-required
        with:
          released_version: ${{ steps.versions.outputs.released-version }}
          next_version: ${{ steps.versions.outputs.changelog-latest-version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}